apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-namespace-networkpolicy
spec:
  generateExisting: true
  rules:
    - name: generate-namespace-specific-networkpolicy
      match:
        resources:
          kinds:
            - Namespace
      generate:
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        name: "np-{{request.object.metadata.name}}"
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        data:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: "np-{{request.object.metadata.name}}"
            labels:
              created-by: kyverno
              namespace: "{{request.object.metadata.name}}"
              policy-type: "default-deny"
          spec:
            podSelector: {}
            policyTypes:
              - Ingress
              - Egress