apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-mutate-validate-enforce
spec:
  validationFailureAction: Enforce
  generateExisting: true
  rules:

    - name: generate-default-networkpolicy
      match:
        resources:
          kinds:
            - Namespace
      generate:
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        name: "np-{{request.object.metadata.name}}"
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        data:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: "np-{{request.object.metadata.name}}"
            labels:
              created-by: kyverno
              namespace: "{{request.object.metadata.name}}"
              policy-type: "default-deny"
          spec:
            podSelector: {}
            policyTypes:
              - Ingress
              - Egress

    - name: mutate-add-security-label
      match:
        resources:
          kinds:
            - Pod
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              +(security): restricted

    - name: validate-security-label-exists
      match:
        resources:
          kinds:
            - Pod
      validate:
        message: "All Pods must include a 'security' label (restricted, baseline, or privileged)."
        pattern:
          metadata:
            labels:
              security: "?*"

    - name: validate-security-label-allowed-values
      match:
        resources:
          kinds:
            - Pod
      validate:
        message: "The 'security' label must be one of [restricted, baseline, privileged]."
        anyPattern:
          - metadata:
              labels:
                security: "restricted"
          - metadata:
              labels:
                security: "baseline"
          - metadata:
              labels:
                security: "privileged"